# Generated by Django 5.0 on 2023-12-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatroom",
            name="max_members",
            field=models.IntegerField(default=1),
        ),
    ]
